version: "2.1"
orbs:
  npm-audit: urahiroshi/npm-audit@1.0.2

jobs:
  diff:
    executor: npm-audit/default
    working_directory: ~/repo/test
    steps:
      - checkout:
          path: ~/repo
      - audit_diff:
          diff_out: .diff.log

workflows:
  build:
    jobs:
      - npm-audit/diff:
          checkout_path: ~/repo
          working_directory: ~/repo/test
