version: "2.1"
orbs:
  npm-audit: urahiroshi/npm-audit@1.0.3

jobs:
  diff:
    executor: npm-audit/default
    working_directory: ~/repo/test
    steps:
      - checkout:
          path: ~/repo
      - npm-audit/audit_diff:
          diff_out: .diff.log
          cache_key_prefix: custom-cache-key

workflows:
  build:
    jobs:
      - diff
